#!/bin/sh
/bin/echo -e "ATV1\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "ATE0\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "ATS0=0\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "ATQ0\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "ATX3\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "AT&C1\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "AT&D1\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "AT+CMEE=1;+CRC=1;+CR=1;+CMOD=0;+CMUT=0\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "AT\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "AT+CFUN=1\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "AT+CMUT=0\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "AT+CLIP=1\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "AT+CLIR=0\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "AT\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "AT+COPS=0\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "AT+CLVL=102\r" > /dev/smd0
/bin/sleep 1
/bin/echo -e "AT+CLVL=51\r" > /dev/smd0
/bin/sleep 1
