#!/bin/sh
echo "Welcome to Vogue Linux"
mkdir -m 0755 /proc
mount -t proc proc /proc
mkdir -m 0755 /sys
mount -t sysfs sys /sys

#Configure Devices
MAKEDEVS

fail() {
    echo "Failed"
    echo "$1"
    exec /bin/sh
}
while [ ! -e /sys/block/mmcblk0 ] ; do
    echo "Waiting for SD Card"
    sleep 1
done

partition=mmcblk0p1

# Try unpartitioned card
if [ ! -e /sys/block/mmcblk0/$partition ] ; then
    partition=mmcblk0
fi

mkdir -m 0777 /sdcard
echo "Running an fsck on the SD card"
dosfsck -y /dev/block/$partition
mount -t vfat -o fmask=0000,dmask=0000,rw,flush,noatime,nodiratime /dev/block/$partition /sdcard
[ $? -eq 0 ] || fail "Failed to mount the SD card. Cannot continue."

root=/sdcard/rootfs.img

if [ -d /sdcard/android ] ; then
    root=/sdcard/android/rootfs.img
fi

mkdir -m 0755 /rfs
losetup /dev/block/loop2 $root
[ $? -eq 0 ] || fail "Failed to find rootfs.img on SD Card. You need to unzip a rootfs zip file to the root of your SD card."
e2fsck -y /dev/block/loop2
mount -t ext2 -o noatime,nodiratime,sync,ro /dev/block/loop2 /rfs
[ $? -eq 0 ] || fail "Failed to mount /data"

#mkdir /rfs/dev
mount -t tmpfs -o size=100K tmpfs /rfs/dev
cp -a /dev/* /rfs/dev

echo "Cleaning up..."
umount -l /proc
umount -l /sys

echo "Switching to rootfs..."
exec switch_root /rfs /init
