#!/bin/sh
case $1 in
    ppp0)
#        if [ ! -e /sys/class/vogue_hw/gsmphone ] ; then
#            /bin/echo -e "ATH\r" > /dev/smd0
#            /bin/sleep 1
#	fi
	/bin/echo -e "PPP connection went down" >> /smodem/ppp.log
	/bin/echo -e "Done!" >> /smodem/ppp.log
        ;;
    ppp1)
	echo 0 > /proc/sys/net/ipv4/ip_forward;
	;;
esac

# Use interface name if linkname is not available
NAME=${LINKNAME:-"$1"}

/system/bin/setprop "net.$NAME.dns1" "$DNS1"
/system/bin/setprop "net.$NAME.dns2" "$DNS2" 
/system/bin/setprop "net.$NAME.local-ip" "$IPLOCAL" 
/system/bin/setprop "net.$NAME.remote-ip" "$IPREMOTE" 
