#!/bin/sh
case $1 in
ppp0)
	/bin/echo -e "PPP connection went down" >> /smodem/ppp.log
	/bin/echo -e "Done!" >> /smodem/ppp.log
	/bin/echo "0" > /smodem/live
	if [ -e /sys/class/vogue_hw/gsmphone ] ; then
		/bin/echo -e "AT+CREG?\r" > /dev/smd0
	else
		/bin/echo -e "AT+COPS?\r" > /dev/smd0
	fi
	;;
ppp1)
	echo 0 > /proc/sys/net/ipv4/ip_forward;
	;;
esac

# Use interface name if linkname is not available
NAME=${LINKNAME:-"$1"}

/system/bin/setprop "net.$NAME.dns1" "$DNS1"
/system/bin/setprop "net.$NAME.dns2" "$DNS2" 
/system/bin/setprop "net.$NAME.local-ip" "$IPLOCAL" 
/system/bin/setprop "net.$NAME.remote-ip" "$IPREMOTE" 
